apiVersion: v1
kind: Pod
metadata:
  generateName: tpu7x-2x2x1-hbm-microbenchmark-
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: 2x2x1
  containers:
  - name: tpu-job
    image: python:3.12
    ports:
    - containerPort: 8431
    securityContext:
      privileged: false
    command:
    - bash
    - -c
    - |
      set -ex
      # install gcloud package
      apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      apt-get update && apt-get install -y google-cloud-cli

      git clone https://github.com/AI-Hypercomputer/accelerator-microbenchmarks.git
      cd accelerator-microbenchmarks
      pip install -r requirements.txt

      ## add new datatypes
      sed -i '/dtype: "bfloat16"/ { p; s/dtype: "bfloat16"/dtype: "float32"/; }' Ironwood/configs/hbm/hbm.yaml
      sed -i '/dtype: "bfloat16"/ { p; s/dtype: "bfloat16"/dtype: "float8"/; }' Ironwood/configs/hbm/hbm.yaml
      cat Ironwood/configs/hbm/hbm.yaml

      python Ironwood/src/run_benchmark.py --config="Ironwood/configs/hbm/hbm.yaml"

      gcloud storage cp ../microbenchmarks/hbm/*.tsv gs://${BUCKET_NAME}/microbenchmarks/hbm/
    resources:
      requests:
        google.com/tpu: 4
      limits:
        google.com/tpu: 4